# ProxyPlayerNotify Config

# This config file contains settings for the BungeePlayer Notify plugin.
# Use this file to customize the join/leave messages and permissions.

# Network Join Message
# This message is displayed when a player joins the network.
# Placeholders available: %player%, %lp_prefix%, %server% (the server player joined).
join_message: "%player% has joined the network (Logged in server: %server%)"

# Servers Switch Message
# This message is displayed when a player switches to a different server.
# Placeholders available: %player%, %last_server% , %server% (the server player joined), %lp_prefix%.
switch_message: "%player% has switched from %last_server% and joined to the %server% server"

# Network Leave Message
# This message is displayed when a player leaves the network.
# Placeholders available: %player%, %lp_prefix%, %last_server% (the last server player was on).
leave_message: "%player% has left the network (Last server: %last_server%)"

# Permissions
# Use these settings to control who can see the join/leave messages.
permission:
  # Enable this if you want to use permissions and want to use next two options.
  permissions: false

  # Notify Messages
  # If this is true and the player doesn't have ppn.notify permission, then their join/leave/message will not be sent.
  notify_message: false

  # Hide Messages
  # If this is true and the player doesn't have ppn.view permission, then they won't see the others' join/switch/leave messages.
  hide_message: false

# Server Names
# Define custom server names here. Players can join/leave/switch to the server using the custom names specified below.
ServerNames:
  example: "example-1"
  lobby: "Hub"

# Disabled Servers
# Define the backend servers where the join/switch/leave messages should not be sent.
DisabledServers:
  - "example-1"
  - "other-backend-server"
