# BungeePlayer Notify Config
# Network Join Message, placeholder avaiable: %player%, %lp_prefix% for luckperms
join_message: "%player% has joined the network!"

# Servers Switch message, placeholder avaiable: %player%, %server% (the server player joined), %lp_prefix% for luckperms
switch_message: "%player% has switched/joined to the %server% server"

# Network Leave message, placeholder avaiable: %player%, %lp_prefix% for luckperms
leave_message: "%player% has left the network"

permission:
  # enable this if you want to have permissions and use next two options
  permissions: false

  # notify messages. If this is true and if the player doesn't have bpn.notify permission then their join/leave/message will not be sent
  notify_message: false

  # hide messages. If this is true and if the player doesn't have bpn.view permission they won't see the others' join/switch/leave messages
  hide_message: false



