name: Build and Publish Jar

on:
  push:
    branches: [ "**" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProxyPlayerNotify-jar
          path: target/*.jar
