name: Build and Publish Jar

on:
  push:
    branches: [ "**" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProxyPlayerNotify-${{ github.sha }}
          path: target/*.jar

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

